$order

# ---------------------------------------------------------
# Build instructions
# ---------------------------------------------------------
TOPTARGETS := all distclean

SUBDIRS := $$(patsubst %/,%,$$(wildcard */))

$$(TOPTARGETS): $$(SUBDIRS)
$$(SUBDIRS):
	$$(MAKE) -C $$@

.PHONY: $$(TOPTARGETS) $$(SUBDIRS)
